# Generated by Django 3.0.3 on 2020-07-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_companyinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='short_description',
            field=models.TextField(default=''),
        ),
    ]
