# Generated by Django 3.0.3 on 2020-07-07 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_companycontacts_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='note',
            field=models.CharField(default='note', max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='WebSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('note', models.CharField(max_length=255)),
                ('company_contacts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='websites', to='company.CompanyContacts')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('note', models.CharField(max_length=255)),
                ('company_contacts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='company.CompanyContacts')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('note', models.CharField(max_length=255)),
                ('company_contacts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='company.CompanyContacts')),
            ],
        ),
    ]
