<<<<<<< HEAD
# Generated by Django 3.0.3 on 2020-08-16 12:14
=======
# Generated by Django 3.0.4 on 2020-08-15 16:20
>>>>>>> 9fab3e108a6b94f920b47136142c99e031ede4a4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20200815_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'active'), ('DELETED', 'deleted')], default='ACTIVE', max_length=255),
        ),
    ]
