# Generated by Django 3.0.3 on 2020-07-07 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20200707_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='company_files/pictures')),
                ('banner', models.ImageField(upload_to='company_files/banners')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
            ],
        ),
        migrations.AlterField(
            model_name='address',
            name='note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='email',
            name='note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='website',
            name='note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='company_files/images')),
                ('company_files', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='company.CompanyFiles')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='company_files/files')),
                ('note', models.CharField(blank=True, max_length=255)),
                ('company_files', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='company.CompanyFiles')),
            ],
        ),
    ]
