# Generated by Django 3.0.3 on 2020-08-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_card_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='role',
            field=models.CharField(choices=[('ADMINISTRATOR', 'administrator'), ('MODERATOR', 'moderator'), ('COMPANY_OWNER', 'company owner')], max_length=255),
        ),
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'active'), ('DELETED', 'deleted')], max_length=255),
        ),
    ]
