# Generated by Django 3.0.3 on 2020-08-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_auto_20200803_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='role',
            field=models.CharField(choices=[('ADMINISTRATOR', 'administrator'), ('MODERATOR', 'moderator'), ('COMPANY_OWNER', 'company owner'), ('USER', 'user')], default='USER', max_length=255),
        ),
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'active'), ('DELETED', 'deleted')], default='ACTIVE', max_length=255),
        ),
    ]
